apiVersion: batch/v1
kind: CronJob
metadata:
  name: crypto-postgres-sync
  namespace: investorcenter
spec:
  schedule: "0 */6 * * *"  # Run every 6 hours
  concurrencyPolicy: Forbid  # Don't run if previous job is still running
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 3
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: crypto-sync
            image: 360358043271.dkr.ecr.us-east-1.amazonaws.com/investorcenter/crypto-postgres-sync:latest
            imagePullPolicy: Always
            command: ["python", "crypto_postgres_sync.py", "--limit", "1000"]
            env:
            - name: REDIS_HOST
              value: "redis-service"
            - name: REDIS_PORT
              value: "6379"
            - name: DB_HOST
              value: "postgres-simple-service"
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: "investorcenter_db"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: password
            - name: LOG_LEVEL
              value: "INFO"
            resources:
              requests:
                memory: "256Mi"
                cpu: "100m"
              limits:
                memory: "512Mi"
                cpu: "200m"