apiVersion: v2
name: investorcenter
description: A Helm chart for InvestorCenter application
type: application
version: 1.0.0
appVersion: "1.0.0"

dependencies:
  - name: redis
    version: 18.2.0
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  
  - name: postgresql
    version: 13.2.0
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled