version: "2"

run:
  timeout: 5m
  tests: false

linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
  settings:
    errcheck:
      exclude-functions:
        - "(*database/sql.Rows).Close"
        - "(*database/sql.Stmt).Close"
        - "(*github.com/jmoiron/sqlx.DB).Close"
    staticcheck:
      checks:
        - "all"
        - "-QF*"
        - "-ST*"

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-dirs:
    - vendor
