apiVersion: apps/v1
kind: Deployment
metadata:
  name: investorcenter-app
  namespace: investorcenter
  labels:
    app: investorcenter-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: investorcenter-app
  template:
    metadata:
      labels:
        app: investorcenter-app
    spec:
      containers:
      - name: investorcenter-app
        image: investorcenter/app:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3000"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
