apiVersion: batch/v1
kind: Job
metadata:
  name: import-all-tickers
  namespace: investorcenter
spec:
  backoffLimit: 3
  ttlSecondsAfterFinished: 3600  # Auto-delete after 1 hour
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: ticker-importer
        image: 360358043271.dkr.ecr.us-east-1.amazonaws.com/investorcenter/ticker-updater:latest
        command: ["python", "/scripts/polygon_comprehensive_import.py"]
        volumeMounts:
        - name: import-script
          mountPath: /scripts
        env:
        - name: DB_HOST
          value: "postgres-simple-service"
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: "investorcenter_db"
        - name: DB_SSLMODE
          value: "disable"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password
        - name: POLYGON_API_KEY
          value: "Q9LhuSPrdj8Fqv9ejYqwXF6AKv7YAsWa"
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
      volumes:
      - name: import-script
        configMap:
          name: polygon-import-script
          defaultMode: 0755