apiVersion: batch/v1
kind: Job
metadata:
  name: migration-008-index
  namespace: investorcenter
spec:
  ttlSecondsAfterFinished: 3600
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: migration
        image: postgres:15
        command: 
        - sh
        - -c
        - |
          echo "Running migration 008: Adding indexes for parsed_data..."
          PGPASSWORD=$DB_PASSWORD psql -h $DB_HOST -U $DB_USER -d $DB_NAME << 'EOF'
          -- Add index on parsed_data column to improve query performance
          CREATE INDEX IF NOT EXISTS idx_sec_filings_parsed_data 
          ON sec_filings(filing_type, ticker_id) 
          WHERE s3_key IS NOT NULL 
            AND (parsed_data IS NULL OR parsed_data = '{}')
            AND filing_type IN ('10-K', '10-Q');

          -- Also add an index on s3_key for faster lookups
          CREATE INDEX IF NOT EXISTS idx_sec_filings_s3_key 
          ON sec_filings(s3_key) 
          WHERE s3_key IS NOT NULL;
          
          SELECT 'Migration complete. Indexes added:' as status;
          SELECT indexname, indexdef 
          FROM pg_indexes 
          WHERE tablename = 'sec_filings' 
          AND indexname IN ('idx_sec_filings_parsed_data', 'idx_sec_filings_s3_key');
          EOF
        env:
        - name: DB_HOST
          value: "postgres-simple-service.investorcenter.svc.cluster.local"
        - name: DB_NAME
          value: "investorcenter_db"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password