apiVersion: batch/v1
kind: Job
metadata:
  name: sec-filing-parser
  namespace: investorcenter
spec:
  ttlSecondsAfterFinished: 86400  # Clean up after 24 hours
  template:
    spec:
      serviceAccountName: sec-downloader-sa
      restartPolicy: OnFailure
      containers:
      - name: sec-filing-parser
        image: 360358043271.dkr.ecr.us-east-1.amazonaws.com/investorcenter/sec-filing-parser:v1
        imagePullPolicy: Always
        env:
        - name: DB_HOST
          value: "postgres-simple-service.investorcenter.svc.cluster.local"
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: "investorcenter_db"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password
        - name: S3_BUCKET
          value: "investorcenter-sec-filings"
        - name: AWS_REGION
          value: "us-east-1"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "1000m"